[package]
name = "adventofcode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.12.0"
rustworkx-core = "0.13.2"
petgraph = "0.6.4"
regex = "1.11.1"
log = "0.4.28"
z3 = "0.19.5"
